# buildspec.yml - AWS CodeBuild specification for CI/CD pipeline

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm@10
      - pnpm --version
      
      - echo "Installing Lambda dependencies..."
      - cd lambda && pnpm install && cd ..

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Packaging Lambda function..."
      
      # Package Lambda function
      - cd lambda && zip -r species-api.zip . && cd ..
      
      # Update Lambda function
      - echo "Updating Lambda function - species-api..."
      - aws lambda update-function-code --function-name nameria-dnd-species-api --zip-file fileb://lambda/species-api.zip --region us-west-2
      
      # Sync frontend files to S3
      - echo "Syncing frontend files to S3..."
      - aws s3 sync frontend/ s3://$S3_BUCKET --delete --region us-west-2
      
      # Get CloudFront distribution ID
      - export CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='nameria-dnd website distribution'].Id" --output text --region us-west-2)
      
      # Invalidate CloudFront cache
      - |
        if [ ! -z "$CLOUDFRONT_ID" ]; then
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*" --region us-west-2
        else
          echo "CloudFront distribution not found, skipping cache invalidation"
        fi

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Deployment successful!"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'lambda/node_modules/**/*'
    - '.pnpm-store/**/*'
